[profile.default]
src = 'src'
libs = ['lib']
fallback_oz = true
via_ir = true
optimizer = true
optimizer_runs = 200
remappings = [
    '@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/',
    '@pythnetwork/=lib/pyth-sdk-solidity/',
    '@uniswap/v3-core/=lib/v3-core/',
    '@uniswap/v3-periphery/=lib/v3-periphery/'
]

[profile.default.zksync]
enable_eravm_extensions = true # Note: System contract calls (NonceHolder and ContractDeployer) can only be called with this set to true

[etherscan]
abstractTestnet = { chain = "11124", url = "https://api-sepolia.abscan.org/api", key = "TACK2D1RGYX9U7MC31SZWWQ7FCWRYQ96AD"}
abstractMainnet = { chain = "2741", url = "https://api.abscan.org/api", key = ""} # You can replace these values or leave them blank to override via CLI